export const browserCoreExamples = [
  "agentme browser status",
  "agentme browser start",
  "agentme browser stop",
  "agentme browser tabs",
  "agentme browser open https://example.com",
  "agentme browser focus abcd1234",
  "agentme browser close abcd1234",
  "agentme browser screenshot",
  "agentme browser screenshot --full-page",
  "agentme browser screenshot --ref 12",
  "agentme browser snapshot",
  "agentme browser snapshot --format aria --limit 200",
  "agentme browser snapshot --efficient",
  "agentme browser snapshot --labels",
];

export const browserActionExamples = [
  "agentme browser navigate https://example.com",
  "agentme browser resize 1280 720",
  "agentme browser click 12 --double",
  'agentme browser type 23 "hello" --submit',
  "agentme browser press Enter",
  "agentme browser hover 44",
  "agentme browser drag 10 11",
  "agentme browser select 9 OptionA OptionB",
  "agentme browser upload /tmp/file.pdf",
  'agentme browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "agentme browser dialog --accept",
  'agentme browser wait --text "Done"',
  "agentme browser evaluate --fn '(el) => el.textContent' --ref 7",
  "agentme browser console --level error",
  "agentme browser pdf",
];
